baseURL: https://dappub.github.io/dappub.com/
languageCode: en-us
title: Dappub
theme: hugo-fresh

params:
  hero:
    tagline: DApp开发平台
    subTagline: 为EOS DApp开发者而生
    image: illustrations/worker.svg
  navbar:
    panelTrigger: false
    logo:
      src: logos/dappub-long.png
      alt: Main navbar logo
    links:
    - text: 服务列表
      url: /#features
  features:
    tagline: 服务列表
    subTagline: 我们提供DApp开发所需的基础工具以及开源协议，帮助你高效构建自己的DApp。
    panels:
    - title: 账户注册协议
      image: illustrations/icons/mouse-globe.svg
      text: 通过交易所提现或者转账的形式帮用户创建账户。
      button:
        text: 项目地址
        url: https://github.com/dapptalking/signupeoseos
      delay: 1
    - title: 资产交易协议
      image: illustrations/icons/laptop-cloud.svg
      text: 在DApp内与其他DApp中的资产直接进行交易。
      button:
        text: 即将上线
        url: /
      delay: 2
    - title: 合约监控系统
      image: illustrations/icons/plug-cloud.svg
      text: 完善的链上日志、指标监控系统。
      button:
        text: 即将上线
        url: /
      delay: 3
  footer:
    image: dappub-long.png
    columns:
    - title: 产品
      links:
      - name: 注册协议
        url: "https://github.com/dappub/signupeoseos"
    - title: 博客
      links:
      - name: Medium
        url: "https://medium.com/@thbourlove"
    followUs:
    - icon: github
      url: "https://github.com/dappub"
    - icon: medium
      url: "https://medium.com/@thbourlove"
    - icon: twitter
      url: "https://twitter.com/thbourlove"
